config:
  abuse-sleuth:rds-databaseName: AbuseSleuth
  abuse-sleuth:rds-instanceCount: "1"
  abuse-sleuth:rds-password:
    secure: AAABAPjMkZHrd4Rv2NweXch3OGWBcHYQMm0J9Ltxt/hvXmGHUtl4k58bZf8=
  abuse-sleuth:rds-public: "false"
  abuse-sleuth:rds-username: dbRoot
  aws:profile: default
  aws:region: eu-west-2
