version: "3.6"
services:
    postgres:
        image: postgres:alpine
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: "abusesleuth"
            POSTGRES_PASSWORD: "password"
            POSTGRES_HOST_AUTH_METHOD: trust
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5

    postgres_is_ready:
        image: postgres:alpine
        depends_on:
            postgres:
                condition: service_healthy

volumes:
    db_data:
