name: "Unit Test on Development"

on:
  push:
    branches: [develop]

jobs:
  test:
    runs_on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Packages
        run: yarn install

      - name: Run Tests
        run: yarn test:unit
